/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard/transactions'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard/subscriptions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardScannerRouteImport } from './routes/dashboard/scanner'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMicroObjectivesRouteImport } from './routes/dashboard/micro-objectives'
import { Route as DashboardInvestmentsRouteImport } from './routes/dashboard/investments'
import { Route as DashboardGoalsRouteImport } from './routes/dashboard/goals'
import { Route as DashboardExportRouteImport } from './routes/dashboard/export'
import { Route as DashboardChallengesRouteImport } from './routes/dashboard/challenges'
import { Route as DashboardBudgetRouteImport } from './routes/dashboard/budget'
import { Route as DashboardBillsRouteImport } from './routes/dashboard/bills'
import { Route as DashboardAssistantRouteImport } from './routes/dashboard/assistant'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScannerRoute = DashboardScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMicroObjectivesRoute =
  DashboardMicroObjectivesRouteImport.update({
    id: '/micro-objectives',
    path: '/micro-objectives',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardInvestmentsRoute = DashboardInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGoalsRoute = DashboardGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExportRoute = DashboardExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChallengesRoute = DashboardChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBudgetRoute = DashboardBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillsRoute = DashboardBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssistantRoute = DashboardAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/bills': typeof DashboardBillsRoute
  '/dashboard/budget': typeof DashboardBudgetRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/export': typeof DashboardExportRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/investments': typeof DashboardInvestmentsRoute
  '/dashboard/micro-objectives': typeof DashboardMicroObjectivesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scanner': typeof DashboardScannerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/bills': typeof DashboardBillsRoute
  '/dashboard/budget': typeof DashboardBudgetRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/export': typeof DashboardExportRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/investments': typeof DashboardInvestmentsRoute
  '/dashboard/micro-objectives': typeof DashboardMicroObjectivesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scanner': typeof DashboardScannerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/bills': typeof DashboardBillsRoute
  '/dashboard/budget': typeof DashboardBudgetRoute
  '/dashboard/challenges': typeof DashboardChallengesRoute
  '/dashboard/export': typeof DashboardExportRoute
  '/dashboard/goals': typeof DashboardGoalsRoute
  '/dashboard/investments': typeof DashboardInvestmentsRoute
  '/dashboard/micro-objectives': typeof DashboardMicroObjectivesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/scanner': typeof DashboardScannerRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/assistant'
    | '/dashboard/bills'
    | '/dashboard/budget'
    | '/dashboard/challenges'
    | '/dashboard/export'
    | '/dashboard/goals'
    | '/dashboard/investments'
    | '/dashboard/micro-objectives'
    | '/dashboard/profile'
    | '/dashboard/scanner'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/transactions'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard/assistant'
    | '/dashboard/bills'
    | '/dashboard/budget'
    | '/dashboard/challenges'
    | '/dashboard/export'
    | '/dashboard/goals'
    | '/dashboard/investments'
    | '/dashboard/micro-objectives'
    | '/dashboard/profile'
    | '/dashboard/scanner'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/transactions'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/dashboard/assistant'
    | '/dashboard/bills'
    | '/dashboard/budget'
    | '/dashboard/challenges'
    | '/dashboard/export'
    | '/dashboard/goals'
    | '/dashboard/investments'
    | '/dashboard/micro-objectives'
    | '/dashboard/profile'
    | '/dashboard/scanner'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/transactions'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scanner': {
      id: '/dashboard/scanner'
      path: '/scanner'
      fullPath: '/dashboard/scanner'
      preLoaderRoute: typeof DashboardScannerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/micro-objectives': {
      id: '/dashboard/micro-objectives'
      path: '/micro-objectives'
      fullPath: '/dashboard/micro-objectives'
      preLoaderRoute: typeof DashboardMicroObjectivesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/investments': {
      id: '/dashboard/investments'
      path: '/investments'
      fullPath: '/dashboard/investments'
      preLoaderRoute: typeof DashboardInvestmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/goals': {
      id: '/dashboard/goals'
      path: '/goals'
      fullPath: '/dashboard/goals'
      preLoaderRoute: typeof DashboardGoalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/export': {
      id: '/dashboard/export'
      path: '/export'
      fullPath: '/dashboard/export'
      preLoaderRoute: typeof DashboardExportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/challenges': {
      id: '/dashboard/challenges'
      path: '/challenges'
      fullPath: '/dashboard/challenges'
      preLoaderRoute: typeof DashboardChallengesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/budget': {
      id: '/dashboard/budget'
      path: '/budget'
      fullPath: '/dashboard/budget'
      preLoaderRoute: typeof DashboardBudgetRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bills': {
      id: '/dashboard/bills'
      path: '/bills'
      fullPath: '/dashboard/bills'
      preLoaderRoute: typeof DashboardBillsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assistant': {
      id: '/dashboard/assistant'
      path: '/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof DashboardAssistantRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAssistantRoute: typeof DashboardAssistantRoute
  DashboardBillsRoute: typeof DashboardBillsRoute
  DashboardBudgetRoute: typeof DashboardBudgetRoute
  DashboardChallengesRoute: typeof DashboardChallengesRoute
  DashboardExportRoute: typeof DashboardExportRoute
  DashboardGoalsRoute: typeof DashboardGoalsRoute
  DashboardInvestmentsRoute: typeof DashboardInvestmentsRoute
  DashboardMicroObjectivesRoute: typeof DashboardMicroObjectivesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardScannerRoute: typeof DashboardScannerRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssistantRoute: DashboardAssistantRoute,
  DashboardBillsRoute: DashboardBillsRoute,
  DashboardBudgetRoute: DashboardBudgetRoute,
  DashboardChallengesRoute: DashboardChallengesRoute,
  DashboardExportRoute: DashboardExportRoute,
  DashboardGoalsRoute: DashboardGoalsRoute,
  DashboardInvestmentsRoute: DashboardInvestmentsRoute,
  DashboardMicroObjectivesRoute: DashboardMicroObjectivesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardScannerRoute: DashboardScannerRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
